export * from './About';
export * from './Contact';
export * from './FloatingNav';
export * from './Footer';
export * from './Header';
export * from './Navbar';
export * from './Portfolio';
export * from './Services';
export * from './FAQ';